# Generated by Django 3.2.6 on 2021-08-24 08:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('boulange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('line_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('pasty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boulange.pastry')),
            ],
        ),
    ]
