# Generated by Django 3.2.6 on 2021-08-23 08:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boulange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakery',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bakery',
            name='city',
            field=models.CharField(choices=[('Paris', 'Paris'), ('Quebec', 'Quebec')], max_length=100),
        ),
    ]
