# Generated by Django 3.2.6 on 2021-08-23 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boulange', '0002_auto_20210823_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakery',
            name='city',
            field=models.CharField(choices=[('Paris', 'Paris'), ('Quebec', 'Quebec'), ('Istanbul', 'Istanbul')], max_length=100),
        ),
        migrations.CreateModel(
            name='Pastry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bakery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
