# Generated by Django 3.2.6 on 2021-09-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boulange', '0006_bakery_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakery',
            name='imageUrl',
            field=models.URLField(blank=True),
        ),
    ]
